### ISSUE TITLE
Found "[" but: its sibling was not an indent Doc.

### ISSUE THREAD

**Issue by bitbangx** [electrovir/prettier-plugin-newline-arrays#38] opened 2024-07-15 08:35 UTC
Using prettier 3.3.3 and this minimal test block

`const a = [];`

I get this error:

`Error: Found "[" but: its sibling was not an indent Doc.: 
    at c:\Projects\kameleon\erp\node_modules\prettier-plugin-multiline-arrays\dist\printer\insert-new-lines.js:57:23
    at walkDoc (c:\Projects\kameleon\erp\node_modules\prettier-plugin-multiline-arrays\dist\printer\child-docs.js:28:10)
    at c:\Projects\kameleon\erp\node_modules\prettier-plugin-multiline-arrays\dist\printer\child-docs.js:41:20
    at Array.every (<anonymous>)
    at walkDoc (c:\Projects\kameleon\erp\node_modules\prettier-plugin-multiline-arrays\dist\printer\child-docs.js:40:18)
    at c:\Projects\kameleon\erp\node_modules\prettier-plugin-multiline-arrays\dist\printer\child-docs.js:41:20
    at Array.every (<anonymous>)
    at walkDoc (c:\Projects\kameleon\erp\node_modules\prettier-plugin-multiline-arrays\dist\printer\child-docs.js:40:18)
    at insertLinesIntoArray (c:\Projects\kameleon\erp\node_modules\prettier-plugin-multiline-arrays\dist\printer\insert-new-lines.js:17:30)
    at printWithMultilineArrays (c:\Projects\kameleon\erp\node_modules\prettier-plugin-multiline-arrays\dist\printer\insert-new-lines.js:419:15)`
    
It seems using a non-empty array it's not causing this issue. Please also note that before updating prettier from 3.2.5 to 3.3.3 it was not happening

this is my .prettierrc

`{
  "plugins": ["prettier-plugin-multiline-arrays"],
  "singleQuote": true,
  "trailingComma": "all",
  "printWidth": 120,
  "multilineArraysNextLinePattern": 3
}
`

**Comment by electrovir** [comment] 2024-07-15 15:12
Uh oh! Thanks for the report, I'll investigate.

**Comment by electrovir** [comment] 2024-07-15 15:39
Oh, I think this is just a duplicate of #32. Please try updating your version for this package. Feel free to reopen if that doesn't fix it for you!

**Closed as not planned by electrovir** 2024-07-15 15:39 UTC
Labels: bug
