### ISSUE TITLE
Typescript annotation forces blank line

### ISSUE THREAD

**Issue by owen-psiq** [electrovir/prettier-plugin-newline-arrays#46] opened 2024-10-31 21:32 UTC
```
    return [
      {
        operation: "update",
        content: "text"
      } as const

    ]
```
The newline before `]` will go away if you remove the `as const` annotation.

**Comment by electrovir** [comment] 2024-12-14 23:54
this appears to also be a duplicate of #41

**Closed as not planned by electrovir** 2024-12-14 23:54 UTC
Labels: bug
