### ISSUE TITLE
map function causes weird wrap

### ISSUE THREAD

**Issue by owen-psiq** [electrovir/prettier-plugin-newline-arrays#45] opened 2024-10-31 21:30 UTC
```
const array = [
  1,
  otherArray.map((it) => !it)]
```

I'd expect it to be formatted like
```
const array = [
  1,
  otherArray.map((it) => it)
]```

**Comment by electrovir** [comment] 2024-12-14 23:45
I think this is a dupe of #41. When I have commas enabled, the formatting does look like what you expect it to be.

**Closed as not planned by electrovir** 2024-12-14 23:45 UTC
Labels: bug
